### ISSUE TITLE
VS2019 Compile Problem

### ISSUE THREAD

**Issue by Wolle86** [niessner/mLib#12]
Datei (Include) kann nicht geöffnet werden: "boost/serialization/array_wrapper.hpp": No such file or directory	
\mLib\include\core-base\common.h	61

**Comment by neeek2303** [comment]
Same problem

**Comment by khakhlyuk** [comment]
in my case just commenting it out helped

**Comment by dazinovic** [comment]
It seems to be a boost issue. Either install a newer version which has the file or try commenting out the include (not sure what it's actually used for here).
