### ISSUE TITLE
mLib compile error in VS2017 + CUDA 9.1

### ISSUE THREAD

**Issue by rayhero** [niessner/mLib#5]
I want to use this lib to build the bundlefusion server using VS2017 + CUDA9.1.
I meet a C2280 error: attempting to reference a deleted function in D3D11Canvas2D.h:
the error happen in auto _e = e.castBillboard:

![2018-02-01 10 33 09](https://user-images.githubusercontent.com/3665120/35658285-868640d6-073b-11e8-8145-dabac180958a.png)

I not sure this error is the IDE bug or the mLib bug?

**Comment by dazinovic** [comment]
Fixed by making _e a const reference. Make sure you also rebuild the libraries from mLibExternal if you are using a newer compiler.

**Comment by 94zhaofang** [comment]
@dazinovic  Hello, I meet C2280 error too, and I use mLib to build the bundlefusion project by VS2015 + CUDA9.1. Could you tell me how to rebuild the libraries from mLibExternal ? Thank you !

**Comment by jackxujh** [comment]
Hi @dazinovic, could you elaborate how do you make `_e` a const reference? I am not sure which line I should change. Meanwhile, how do I *rebuild the libraries from mLibExternal*?

> Fixed by making _e a const reference. Make sure you also rebuild the libraries from mLibExternal if you are using a newer compiler.

**Comment by dazinovic** [comment]
_e is already a const reference in the code. You don't need to change anything there. For each library you want to link against, you will have to build it yourself. There is no general guide for this, it depends on the specific libraries.

**Comment by jackxujh** [comment]
Do you mean that *mLib* is not built when the code includes it in a Visual Studio project?

**Comment by chethanab16** [comment]
@jackxujh did you solved this problem , could you suggest how to do it 


Severity	Code	Description	Project	File	Line	Suppression State
Error	C2280	'ml::D3D11Canvas2D::ElementBillboard::ElementBillboard(const ml::D3D11Canvas2D::ElementBillboard &)': attempting to reference a deleted function	FriedLiver	d:\azure_kinect_bundlefusion\bundlefusion-master1_2017_retar\external\mlib\include\application-d3d11\d3d11canvas2d.h	302

**Comment by chethanab16** [comment]
@dazinovic could you please explain me more about it I didn't understand "**For each library you want to link against, you will have to build it yourself. There is no general guide for this, it depends on the specific libraries."**

**Comment by chethanab16** [comment]
@rayhero could you suggest me how to solve this problem ''
![bundle fusion stuck_kinect_2](https://user-images.githubusercontent.com/34049539/93160126-a9679580-f74a-11ea-9e12-6df4df5b65c2.png)

thankyou

**Comment by KernelA** [comment]
I changed:
```
auto _e = e.castBillboard();
```
to
```
auto& _e = e.castBillboard();
```
